% recreate.m
% pulls information from figures generated by bf1.m and makes a
% comparative chart

l = .1;
Nhats = 21;
g_l_fcn = @(an_x_grid) (an_x_grid .^2)*1e3 + g_0;
g_0 = .5; %mS/cm^2
x_vals = linspace(0,l,Nhats)';
true_g_l = g_l_fcn(x_vals);

Trange = [5 10 30];
Ntemp = [2 5 10 20 40];



g_l_info = zeros(Nhats,numel(Ntemp), numel(Trange));

for R = 1:numel(Trange)
  for N = 1:numel(Ntemp)

    try
      fname = ['hat_' num2str(Trange(R)) ',' num2str(Ntemp(N)) '.fig'];
      open(fname);
      h = gcf;
      line = findall(h, 'Type', 'Line');
      g_l_info(:,N,R) = get(line(5), 'ydata')';
    catch
      g_l_info(:,N,R) = -1;
    end

  end
end

rep_true_g_l = repmat(true_g_l, [1, numel(Ntemp), numel(Trange)]);

sum_sq_error = sum((g_l_info - rep_true_g_l).^2);

plottable = reshape(sum_sq_error, numel(Ntemp),numel(Trange))';